#!/bin/bash

#SBATCH -p main

#SBATCH --mem=1024
#SBATCH --job-name=s33_planar
#SBATCH --output=s33_planar.out
#SBATCH --error=s33_planar.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --tasks-per-node=8
#SBATCH --nodes=1

#SBATCH --time=20:00:00

module load gromacs/single/2016.1

cd /scratch/eixeres/Version_v2/Planar_Systems/s33

gmx grompp -f Mini_v2.mdp -c sam33_water_ptensor_v2.gro -p 33pc_ptensor_v2.top -o Mini_sam33_water_ptensor_v2.tpr -maxwarn 9
gmx mdrun -deffnm Mini_sam33_water_ptensor_v2 -maxh 200 -v 
gmx grompp -f NVT_8ns_v2.mdp -c Mini_sam33_water_ptensor_v2.gro -p 33pc_ptensor_v2.top -o NVT_sam33_water_ptensor_v2.tpr -maxwarn 9

gmx mdrun -s NVT_sam33_water_ptensor_v2.tpr -deffnm  NVT_sam33_water_ptensor_v2 -maxh 20 -v 