#!/bin/bash

#SBATCH -p gpu-main
#SBATCH --gres=gpu:2

#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=s0_w5_4gpu
#SBATCH --output=s0_w5000_gpu_4.out
#SBATCH --error=s0_w5000_gpu_4.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=8
#SBATCH --nodes=1

#SBATCH --time=120:00:00

module load gromacs/single/2016.1

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2.2/s0_w5000

mdrun_gpu -cpi NVT_sam0_water5000.cpt -s NVT_sam0_water5000.tpr -deffnm NVT_sam0_water5000 -maxh 120 -v 

