#!/bin/bash

#SBATCH -p main

#SBATCH --mem=2048
#SBATCH --job-name=1n_s11_w10_0
#SBATCH --output=1n_s11_w10000_0.out
#SBATCH --error=1n_s11_w10000_0.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --tasks-per-node=8
#SBATCH --nodes=1

#SBATCH --time=200:00:00

module load gromacs/single/2016

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s11_w10000

gmx grompp -f Mini_v2.mdp -c sam11_water10000.gro -p 11pc_10000.top -o Mini_sam11_water10000.tpr -maxwarn 9
gmx mdrun -deffnm Mini_sam11_water10000 -maxh 200 -v 
gmx grompp -f NVT_100ns_v2.mdp -c Mini_sam11_water10000.gro -p 11pc_10000.top -o NVT_sam11_water10000.tpr -maxwarn 9

gmx mdrun -s NVT_sam11_water10000.tpr -deffnm  NVT_sam11_water10000 -maxh 200 -v 

RUNTIME=$(($(date +%s)-$STARTTIME))

echo "the job took $RUNTIME seconds..."

if [[ $RUNTIME -lt 10 ]]; then
   echo "job took less than 10 seconds to run, aborting."
   exit
else
   echo "everything fine..."
   sbatch /scratch/eixeres/Version_v2/scripts/11_w10000/1n_s11_w10000_1
   fi

