#!/bin/bash

#SBATCH -p main

#SBATCH --mem=2048
#SBATCH --job-name=waterbox
#SBATCH --output=waterbox.out

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --tasks-per-node=8
#SBATCH --nodes=1

#SBATCH --time=200:00:00

module load slurm 

module load gromacs/single/5.1.3

cd /scratch/eixeres/Version_v2/ptensor/waterbox

#gmx grompp -f Mini_water_v2.mdp -c waterbox_ptensor_v2.gro -p waterbox_v2.top -o Mini_water.tpr
#mpirun -np 8 gmx mdrun -deffnm Mini_water 
 
#gmx grompp -f NVT_water_v2.mdp -c Mini_water.gro -p waterbox_v2.top -o NVT_water.tpr 
mpirun -np 8 gmx mdrun -deffnm NVT_water 
 
gmx grompp -f NPT_water_v2.mdp -c NVT_water.gro -p waterbox_v2.top -o NPT_water.tpr 
mpirun -np 8 gmx mdrun -deffnm NPT_waterbox_ptensor_v2 
 
cp -r /scratch/eixeres/NewVersion4/s41_w7000 /home/eixeres/NewVersion4/FINISHED