#!/bin/bash

#SBATCH -p gpu-main
#SBATCH --gres=gpu:2

#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=s11_w1_4gpu
#SBATCH --output=s11_w1000_gpu_4.out
#SBATCH --error=s11_w1000_gpu_4.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=8
#SBATCH --nodes=1

#SBATCH --time=120:00:00

module load gromacs/single/2016

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s11_w1000

mdrun_gpu -cpi NVT_sam11_water1000.cpt -s NVT_sam11_water1000.tpr -deffnm NVT_sam11_water1000 -maxh 120 -v 

cp -r /scratch/eixeres/Version_v2/s11_w1000 /home/eixeres/Version_v2/FINISHED_extended/
