#!/bin/bash

#SBATCH -p gpu-main
#SBATCH --gres=gpu:2

#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=s22_w8_4gpu
#SBATCH --output=s22_w8000_gpu_4.out
#SBATCH --error=s22_w8000_gpu_4.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=8
#SBATCH --nodes=1

#SBATCH --time=120:00:00

module load gromacs/single/2016

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s22_w8000

mdrun_gpu -cpi NVT_sam22_water8000.cpt -s NVT_sam22_water8000.tpr -deffnm NVT_sam22_water8000 -maxh 120 -v 

cp -r /scratch/eixeres/Version_v2/s22_w8000 /home/eixeres/Version_v2/FINISHED_extended/
