#!/bin/bash

#SBATCH -p gpu-main
#SBATCH --gres=gpu:2

#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=s50_w5_0gpu
#SBATCH --output=s50_w5000_gpu_0.out
#SBATCH --error=s50_w5000_gpu_0.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=8
#SBATCH --nodes=1

#SBATCH --time=120:00:00

module load gromacs/single/2016.1

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2.2/s50_w5000

gmx grompp -f Mini_v2.mdp -c sam50_water5000.gro -p 50pc_5000.top -o Mini_sam50_water5000.tpr -maxwarn 9
mdrun_gpu -deffnm Mini_sam50_water5000 -maxh 120 -v 
gmx grompp -f NVT_200ns_v2.2.mdp -c Mini_sam50_water5000.gro -p 50pc_5000.top -o NVT_sam50_water5000.tpr -maxwarn 9

mdrun_gpu -s NVT_sam50_water5000.tpr -deffnm NVT_sam50_water5000 -maxh 120 -v 

RUNTIME=$(($(date +%s)-$STARTTIME))

echo "the job took $RUNTIME seconds..."

if [[ $RUNTIME -lt 10 ]]; then
   echo "job took less than 10 seconds to run, aborting."
   exit
else
   echo "everything fine..."
   sbatch /scratch/eixeres/Version_v2.2/scripts/s50_w5000/s50_w5000_gpu_1
   fi

