#!/bin/bash

#SBATCH -p gpu-main
#SBATCH --gres=gpu:2

#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=s22_w6_0gpu
#SBATCH --output=1n_s22_w6500_gpu_0.out
#SBATCH --error=1n_s22_w6500_gpu_0.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=8
#SBATCH --nodes=1

#SBATCH --time=120:00:00

module load gromacs/single/2016

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s22_w6500

gmx grompp -f Mini_v2.mdp -c sam22_water6500.gro -p 22pc_6500.top -o Mini_sam22_water6500.tpr -maxwarn 9
 mdrun_gpu -deffnm Mini_sam22_water6500 -maxh 120 -v 
gmx grompp -f NVT_60ns_v2.mdp -c Mini_sam22_water6500.gro -p 22pc_6500.top -o NVT_sam22_water6500.tpr -maxwarn 9

 mdrun_gpu -s NVT_sam22_water6500.tpr -deffnm  NVT_sam22_water6500 -maxh 120 -v 

RUNTIME=$(($(date +%s)-$STARTTIME))

echo "the job took $RUNTIME seconds..."

if [[ $RUNTIME -lt 10 ]]; then
   echo "job took less than 10 seconds to run, aborting."
   exit
else
   echo "everything fine..."
   sbatch /scratch/eixeres/Version_v2/scripts/22_w6500/1n_s22_w6500_gpu_1
   fi

