#!/bin/bash

#SBATCH -p gpu-main
#SBATCH --gres=gpu:2

#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=s11_w8_0gpu
#SBATCH --output=s11_w8000_gpu_0.out
#SBATCH --error=s11_w8000_gpu_0.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=8
#SBATCH --nodes=1

#SBATCH --time=120:00:00

module load gromacs/single/2016

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s11_w8000

gmx convert-tpr -s NVT_sam11_water8000.tpr -until 200000 -o NVT_sam11_water8000.tpr 

mdrun_gpu -s NVT_sam11_water8000.tpr -deffnm NVT_sam11_water8000 -maxh 120 -v 

RUNTIME=$(($(date +%s)-$STARTTIME))

echo "the job took $RUNTIME seconds..."

if [[ $RUNTIME -lt 10 ]]; then
   echo "job took less than 10 seconds to run, aborting."
   exit
else
   echo "everything fine..."
   sbatch /scratch/eixeres/Version_v2/scripts/s11_w8000/s11_w8000_gpu_1
   fi

