#!/bin/bash

#SBATCH -p gpu-main
#SBATCH --gres=gpu:2

#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=s44_w1_0gpu
#SBATCH --output=s44_w1000_gpu_0.out
#SBATCH --error=s44_w1000_gpu_0.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=8
#SBATCH --nodes=1

#SBATCH --time=120:00:00

module load gromacs/single/2016.1

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s44_w1000

gmx convert-tpr -s NVT_sam44_water1000.tpr -until 200000 -o NVT_sam44_water1000.tpr 

mdrun_gpu -cpi NVT_sam44_water1000.cpt -s NVT_sam44_water1000.tpr -deffnm NVT_sam44_water1000 -maxh 120 -v 

RUNTIME=$(($(date +%s)-$STARTTIME))

echo "the job took $RUNTIME seconds..."

if [[ $RUNTIME -lt 10 ]]; then
   echo "job took less than 10 seconds to run, aborting."
   exit
else
   echo "everything fine..."
   sbatch /scratch/eixeres/Version_v2/scripts/s44_w1000/s44_w1000_gpu_1
   fi

