#!/bin/bash

#SBATCH -p main

#SBATCH --mem=2048
#SBATCH --job-name=s44_w1_9
#SBATCH --output=s44_w1000_9.out
#SBATCH --error=s44_w1000_9.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --tasks-per-node=8
#SBATCH --nodes=1

#SBATCH --time=200:00:00

module load gromacs/single/2016.1

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s44_w1000

gmx mdrun -cpi NVT_sam44_water1000.cpt -s NVT_sam44_water1000.tpr -deffnm  NVT_sam44_water1000 -maxh 200 -v 

cp -r /scratch/eixeres/Version_v2/s44_w1000 /home/eixeres/Version_v2/FINISHED_extended/
