#!/bin/bash

#SBATCH -p gpu-main
#SBATCH --gres=gpu:2

#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=s33_w4_4gpu
#SBATCH --output=s33_w4000_gpu_4.out
#SBATCH --error=s33_w4000_gpu_4.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=8
#SBATCH --nodes=1

#SBATCH --time=120:00:00

module load gromacs/single/2016.1

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2.2/s33_w4000

mdrun_gpu -cpi NVT_sam33_water4000.cpt -s NVT_sam33_water4000.tpr -deffnm NVT_sam33_water4000 -maxh 120 -v 

