#!/bin/bash

#SBATCH -p main

#SBATCH --mem=2048
#SBATCH --job-name=s0_w2_0
#SBATCH --output=s0_w2000_0.out
#SBATCH --error=s0_w2000_0.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --tasks-per-node=8
#SBATCH --nodes=1

#SBATCH --time=200:00:00

module load gromacs/single/2016.1

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s0_w2000

gmx convert-tpr -s NVT_sam0_water2000.tpr -until 200000 -o NVT_sam0_water2000.tpr 

gmx mdrun -cpi NVT_sam0_water2000.cpt -s NVT_sam0_water2000.tpr -deffnm  NVT_sam0_water2000 -maxh 200 -v 

RUNTIME=$(($(date +%s)-$STARTTIME))

echo "the job took $RUNTIME seconds..."

if [[ $RUNTIME -lt 10 ]]; then
   echo "job took less than 10 seconds to run, aborting."
   exit
else
   echo "everything fine..."
   sbatch /scratch/eixeres/Version_v2/scripts/s0_w2000/s0_w2000_1
   fi

