#!/bin/bash

#SBATCH -p main

#SBATCH --mem=2048
#SBATCH --job-name=s22_w6_9
#SBATCH --output=s22_w6500_9.out
#SBATCH --error=s22_w6500_9.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --tasks-per-node=8
#SBATCH --nodes=1

#SBATCH --time=200:00:00

module load gromacs/single/2016.1

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s22_w6500

gmx mdrun -cpi NVT_sam22_water6500.cpt -s NVT_sam22_water6500.tpr -deffnm  NVT_sam22_water6500 -maxh 200 -v 

cp -r /scratch/eixeres/Version_v2/s22_w6500 /home/eixeres/Version_v2/FINISHED_extended/
