#!/bin/bash

#SBATCH -p main

#SBATCH --mem=2048
#SBATCH --job-name=s50_w7_4
#SBATCH --output=s50_w7000_4.out
#SBATCH --error=s50_w7000_4.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --tasks-per-node=8
#SBATCH --nodes=1

#SBATCH --time=200:00:00

module load gromacs/single/2016

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s50_w7000

gmx mdrun -cpi NVT_sam50_water7000.cpt -s NVT_sam50_water7000.tpr -deffnm  NVT_sam50_water7000 -maxh 200 -v 

cp -r /scratch/eixeres/Version_v2/s50_w7000 /home/eixeres/Version_v2/FINISHED_extended/
