#!/bin/bash

#SBATCH -p gpu-main
#SBATCH --gres=gpu:2

#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=s33_w2_9gpu
#SBATCH --output=s33_w2000_gpu_9.out
#SBATCH --error=s33_w2000_gpu_9.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=8
#SBATCH --nodes=1

#SBATCH --time=120:00:00

module load gromacs/single/2016.1

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s33_w2000

mdrun_gpu -cpi NVT_sam33_water2000.cpt -s NVT_sam33_water2000.tpr -deffnm NVT_sam33_water2000 -maxh 120 -v 

cp -r /scratch/eixeres/Version_v2/s33_w2000 /home/eixeres/Version_v2/FINISHED_extended/
