#!/bin/bash

#SBATCH -p gpu-main
#SBATCH --gres=gpu:2

#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=s44_w2_4gpu
#SBATCH --output=1n_s44_w2000_gpu_4.out
#SBATCH --error=1n_s44_w2000_gpu_4.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --ntasks=8
#SBATCH --nodes=1

#SBATCH --time=120:00:00

module load gromacs/single/2016

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s44_w2000

mdrun_gpu -cpi NVT_sam44_water2000.cpt -s NVT_sam44_water2000.tpr -deffnm  NVT_sam44_water2000 -maxh 120 -v 

cp -r /scratch/eixeres/Version_v2/s44_w2000 /home/eixeres/Version_v2/FINISHED/
