#!/bin/bash

#SBATCH -p main

#SBATCH --mem=2048
#SBATCH --job-name=1n_s0_w1_4
#SBATCH --output=1n_s0_w1000_4.out
#SBATCH --error=1n_s0_w1000_4.err

#SBATCH --mail-user=laila.e@fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --mail-type=fail

#SBATCH --tasks-per-node=8
#SBATCH --nodes=1

#SBATCH --time=200:00:00

module load gromacs/single/2016

STARTTIME=$(date +%s)


cd /scratch/eixeres/Version_v2/s0_w1000

gmx mdrun -cpi NVT_sam0_water1000.cpt -s NVT_sam0_water1000.tpr -deffnm  NVT_sam0_water1000 -maxh 200 -v 

cp -r /scratch/eixeres/Version_v2/s0_w1000 /home/eixeres/Version_v2/FINISHED/
